#pragma once

/*
 * ui_icons.h - Icon definitions for Hestia32 UI
 *
 * Uses Phosphor Regular icon font (https://phosphoricons.com).
 *
 * TO GENERATE THE FONT FILES (one-time setup):
 *   Run:  tools/gen_phosphor_fonts.sh
 *   This downloads Phosphor.ttf and runs lv_font_conv to produce:
 *     src/core/ui/fonts/lv_font_hestia_icons_28.c
 *     src/core/ui/fonts/lv_font_hestia_icons_20.c
 *   Then set HESTIA_ICONS_CUSTOM 1 below, rebuild, and flash.
 *
 * Requires: node.js + npm (for lv_font_conv), curl
 */

#define HESTIA_ICONS_CUSTOM 1  /* Set to 1 after running gen_phosphor_fonts.sh */

#if HESTIA_ICONS_CUSTOM

/* ---------- Phosphor icon font (generated by gen_phosphor_fonts.sh) ---------- */
LV_FONT_DECLARE(lv_font_hestia_icons_48)
LV_FONT_DECLARE(lv_font_hestia_icons_28)
LV_FONT_DECLARE(lv_font_hestia_icons_20)

#define ICON_FONT_48   (&lv_font_hestia_icons_48)
#define ICON_FONT_28   (&lv_font_hestia_icons_28)
#define ICON_FONT_20   (&lv_font_hestia_icons_20)

/*
 * UTF-8 encodings for Phosphor Regular glyphs used in this project.
 * All codepoints are in the Unicode Private Use Area (U+E000–U+EFFF),
 * encoded as 3-byte UTF-8:  0xEE 0x??  0x??
 *
 * Reference: https://github.com/phosphor-icons/web  (src/regular/style.css)
 * https://www.compart.com/en/unicode/U+E288
 */
#define ICON_HEATING    "\xEE\x97\x8A"  /* thermometer-hot   U+E5CA */
#define ICON_COOLING    "\xEE\x96\xAA"  /* snowflake         U+E5AA */
#define ICON_FAN        "\xEE\xA7\xB2"  /* fan               U+E9F2 */
#define ICON_HUMIDITY   "\xEE\x88\x90"  /* drop              U+E210 */
#define ICON_HOT_WATER  "\xEE\xA0\x9E"  /* bathtub           U+E81E */
#define ICON_REVERSING  "\xEE\x82\x86"  /* arrows-left-right U+E086 */
#define ICON_SETTINGS   "\xEE\x89\xB0"  /* gear              U+E270 */
#define ICON_BACK       "\xEE\x81\x98"  /* arrow-left        U+E058 */
#define ICON_ARROW_LEFT "\xEE\x81\x98"  /* arrow-left        U+E058 */
#define ICON_ARROW_RIGHT "\xEE\x81\x9A" /* arrow-right       U+E05A */
#define ICON_WIFI       "\xEE\x93\xAA"  /* wifi-high         U+E4EA */
#define ICON_BRIGHTNESS "\xEE\x91\xB2"  /* sun               U+E472 */
#define ICON_CLOCK      "\xEE\x86\x9A"  /* clock             U+E19A */
#define ICON_GLOBE      "\xEE\x8A\x88"  /* globe             U+E288 */
#define ICON_THERMOSTAT "\xEE\x90\xB4"  /* sliders-horiz.    U+E434 */
#define ICON_THEME      "\xEE\x9B\x88"  /* palette           U+E6C8 */
#define ICON_MODEL      "\xEE\x98\x90"  /* cpu               U+E610 */
#define ICON_WIRING     "\xEE\xA5\x86"  /* plug              U+E946 */
#define ICON_WRENCH     "\xEE\x97\x94"  /* wrench            U+E5D4 */
#define ICON_OK         "\xEE\x86\x84"  /* check-circle      U+E184 */
#define ICON_CLOSE      "\xEE\x93\xB8"  /* x-circle          U+E4F8 */
#define ICON_WARNING    "\xEE\x93\xA2"  /* warning-circle    U+E4E2 */
#define ICON_BOOST      "\xEE\x8F\xBE"  /* rocket-launch     U+E3FE */
#define ICON_ECO        "\xEE\x8B\x9A"  /* leaf              U+E2DA */
#define ICON_SYNC       "\xEE\x82\x94"  /* arrows-clockwise  U+E094 */
#define ICON_RESTART    "\xEE\x82\x94"  /* arrows-clockwise  U+E094 (restart/reboot) */
#define ICON_PROTOCOL   "\xEE\x83\xB2"  /* broadcast         U+E0F2 */
#define ICON_SIGNAL     "\xEE\x85\x84"  /* cell-signal-high  U+E144 */

#else

/* ---------- LVGL built-in symbol fallbacks (always available) ---------- */
#define ICON_FONT_28   NULL
#define ICON_FONT_20   NULL

#define ICON_HEATING    LV_SYMBOL_WARNING
#define ICON_COOLING    LV_SYMBOL_MINUS
#define ICON_FAN        LV_SYMBOL_REFRESH
#define ICON_HUMIDITY   LV_SYMBOL_DOWNLOAD
#define ICON_HOT_WATER  LV_SYMBOL_AUDIO
#define ICON_SETTINGS   LV_SYMBOL_SETTINGS
#define ICON_BACK       LV_SYMBOL_LEFT
#define ICON_WIFI       LV_SYMBOL_WIFI
#define ICON_BRIGHTNESS LV_SYMBOL_CHARGE
#define ICON_CLOCK      LV_SYMBOL_BELL
#define ICON_THERMOSTAT LV_SYMBOL_EDIT
#define ICON_THEME      LV_SYMBOL_IMAGE
#define ICON_MODEL      LV_SYMBOL_USB
#define ICON_WIRING     LV_SYMBOL_POWER
#define ICON_OK         LV_SYMBOL_OK
#define ICON_CLOSE      LV_SYMBOL_CLOSE
#define ICON_WARNING    LV_SYMBOL_WARNING
#define ICON_BOOST      LV_SYMBOL_UP
#define ICON_ECO        LV_SYMBOL_CHARGE
#define ICON_SYNC       LV_SYMBOL_REFRESH
#define ICON_PROTOCOL   LV_SYMBOL_WIFI
#define ICON_SIGNAL     LV_SYMBOL_WIFI

#endif /* HESTIA_ICONS_CUSTOM */
